apiVersion: apps/v1
kind: Deployment
metadata:
  name: backenddeployment
  labels:
    app: backenddeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backenddeployment
  template:
    metadata:
      labels:
        app: backenddeployment
    spec:
      containers:
      - name: backendpod
        image: localhost:5000/excel_backend:0.0.1
        ports:
        - containerPort: 9000
        env:
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: postgresql-root-username
        - name: DATABASE_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: postgresql-secret
              key: postgresql-root-password
        - name: DATABASE_NAME
          valueFrom: 
            configMapKeyRef:
              name: postgresql-configmap
              key: database_name
        - name: DATABASE_HOST
          valueFrom: 
            configMapKeyRef:
              name: postgresql-configmap
              key: database_host
        - name: DATABASE_PORT
          valueFrom: 
            configMapKeyRef:
              name: postgresql-configmap
              key: database_port
        - name: SECRET_KEY
          valueFrom:
            configMapKeyRef:
              name: django-configs
              key: django_secret_key
        - name: STATIC_URL
          valueFrom:
            configMapKeyRef:
              name: django-configs
              key: django_static_url
---
apiVersion: v1
kind: Service
metadata:
  name: backend-deployment-service
spec:
  selector:
    app: backenddeployment
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30001
