apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendeployment
  labels:
    app: frontendeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontendeployment
  template:
    metadata:
      labels:
        app: frontendeployment
    spec:
      containers:
      - name: frontendpod
        image: localhost:5000/excel_frontend:0.0.1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-deployment-service
spec:
  selector:
    app: frontendeployment
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30000
