apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgreqsl-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: postgresql-root-username
        - name: POSTGRES_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: postgresql-secret
              key: postgresql-root-password
        - name: POSTGRES_DB
          valueFrom: 
            configMapKeyRef:
              name: postgresql-configmap
              key: database_name
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432